service: serverless-security-hub
frameworkVersion: '1'

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  logRetentionInDays: 7
  memorySize: 128
  versionFunctions: false
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'securityhub:EnableSecurityHub'
      Resource: '*'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  remediation:
    handler: bin/main
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.config'
            detail-type:
              - 'Config Rules Compliance Change'
            detail:
              configRuleName:
                - 'securityhub-enabled'
              messageType:
                - 'ComplianceChangeNotification'
              newEvaluationResult:
                complianceType:
                  - 'NON_COMPLIANT'

resources:
  Resources:
    SecurityHubEnabled:
      Type: AWS::Config::ConfigRule
      Properties:
        ConfigRuleName: securityhub-enabled
        Source:
          Owner: AWS
          SourceIdentifier: SECURITYHUB_ENABLED
