service: serverless-access-key

frameworkVersion: '1'

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  logRetentionInDays: 7
  memorySize: 128
  versionFunctions: false
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'iam:ListUsers'
        - 'iam:ListAccessKeys'
        - 'iam:UpdateAccessKey'
      Resource: '*'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  inactivate:
    handler: bin/main
    events:
      - schedule: rate(1 day)
